# -*- coding: utf-8 -*-
"""hello_dunia.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10YGf9p57H5-BBlHrTrXRtL3d2RkQpYfe
"""

print ('Hello Dunia')